-- ============================================================================
-- Canada's provinces, and a province on every Canadian city.
--
-- Linda, 20 Sep 2026, wants to add schools in the United States and Canada.
-- Paul: "in order to do this correctly, we need to have the users add Country,
-- State / Province, City, School name."
--
-- He is right, and Canada could not do it at all: `regions` held 51 rows, all
-- American, and of 505 Canadian cities NOT ONE carried a province. So Canada
-- had a flat list of 505 cities from Victoria to St John's with nothing to
-- narrow it by, and a school added in it was filed under a bare city name.
--
-- That is the Annandale bug waiting to happen on a bigger scale. There are two
-- Sainte-Catherines in Quebec and a Vanier in two parts of Ontario; London,
-- Ontario and London, England already share a name in this database, as do
-- Windsor, Hamilton and Victoria. Without a province, "London, Canada" and
-- "London, United Kingdom" are the only things keeping those apart, and two
-- teachers in Ontario can be handed a degree 3 they never earned.
--
-- PROVINCE CENTRES are the mean of that province's towns, not the geographic
-- centre. Canadian provinces are enormous and almost everybody lives along one
-- edge of them: the middle of Ontario is in Hudson Bay. The centre is only a
-- fallback map point for a school added in a town the gazetteer has never heard
-- of, so "where the people are" is the more useful answer. Nunavut has no towns
-- in the gazetteer at all and uses Iqaluit, which is where any school would be.
--
-- The city backfill matches on name, which is safe here and was checked: all
-- 505 names resolve to exactly one province. The two that appear twice —
-- Sainte-Catherine and Vanier — are twice in the SAME province.
-- ============================================================================

insert into public.regions (country_code, code, name, latitude, longitude) values
('CA', 'AB', 'Alberta', 52.03180, -113.71407),
  ('CA', 'BC', 'British Columbia', 49.38408, -122.71587),
  ('CA', 'MB', 'Manitoba', 49.78784, -97.63495),
  ('CA', 'NB', 'New Brunswick', 46.05804, -65.85671),
  ('CA', 'NL', 'Newfoundland and Labrador', 47.81210, -53.86442),
  ('CA', 'NT', 'Northwest Territories', 62.45411, -114.37248),
  ('CA', 'NS', 'Nova Scotia', 44.95004, -63.02571),
  ('CA', 'NU', 'Nunavut', 63.74670, -68.51700),
  ('CA', 'ON', 'Ontario', 43.94385, -79.46363),
  ('CA', 'PE', 'Prince Edward Island', 46.23459, -63.12560),
  ('CA', 'QC', 'Quebec', 45.97203, -73.21219),
  ('CA', 'SK', 'Saskatchewan', 51.63881, -106.04255),
  ('CA', 'YT', 'Yukon', 60.71611, -135.05375)
on conflict (country_code, code) do update
  set name = excluded.name, latitude = excluded.latitude, longitude = excluded.longitude;

-- ── every Canadian city gets its province ──────────────────────────────────
with m(name, code) as (values
('Abbotsford','BC'),
  ('Agincourt North','ON'),
  ('Agincourt South-Malvern West','ON'),
  ('Ahuntsic-Cartierville','QC'),
  ('Airdrie','AB'),
  ('Ajax','ON'),
  ('Alliston','ON'),
  ('Alma','QC'),
  ('Alta Vista','ON'),
  ('Amos','QC'),
  ('Ancaster','ON'),
  ('Annex','ON'),
  ('Arbutus Ridge','BC'),
  ('Arcola East','SK'),
  ('Armdale','NS'),
  ('Auburn Bay','AB'),
  ('Aurora','ON'),
  ('Aylmer','QC'),
  ('Baie-Comeau','QC'),
  ('Banbury-Don Mills','ON'),
  ('Barrie','ON'),
  ('Bathurst Manor','ON'),
  ('Bay Street Corridor','ON'),
  ('Bayview Village','ON'),
  ('Beaconsfield','QC'),
  ('Beauport','QC'),
  ('Bedford','NS'),
  ('Bedford Park-Nortown','ON'),
  ('Belleville','ON'),
  ('Beloeil','QC'),
  ('Beltline','AB'),
  ('Bendale','ON'),
  ('Birchcliffe-Cliffside','ON'),
  ('Black Creek','ON'),
  ('Blainville','QC'),
  ('Blundell','BC'),
  ('Boisbriand','QC'),
  ('Bolton','ON'),
  ('Boucherville','QC'),
  ('Bowmanville','ON'),
  ('Bracebridge','ON'),
  ('Brampton','ON'),
  ('Brandon','MB'),
  ('Brant','ON'),
  ('Brantford','ON'),
  ('Bridlewood','ON'),
  ('Brighouse-City Centre','BC'),
  ('Broadmoor','BC'),
  ('Brocklehurst','BC'),
  ('Brockville','ON'),
  ('Brookhaven-Amesbury','ON'),
  ('Brooklin','ON'),
  ('Brossard','QC'),
  ('Buckingham','QC'),
  ('Burlington','ON'),
  ('Burnaby','BC'),
  ('Caledon','ON'),
  ('Calgary','AB'),
  ('Cambridge','ON'),
  ('Campbell River','BC'),
  ('Camrose','AB'),
  ('Candiac','QC'),
  ('Carey','BC'),
  ('Cariboo','BC'),
  ('Cartierville','QC'),
  ('Central Coquitlam','BC'),
  ('Central Lonsdale','BC'),
  ('Central Saanich','BC'),
  ('Centretown','ON'),
  ('Chambly','QC'),
  ('Charlesbourg','QC'),
  ('Charlottetown','PE'),
  ('Chatham','ON'),
  ('Chestermere','AB'),
  ('Chicoutimi','QC'),
  ('Chilliwack','BC'),
  ('Chilliwack-Downtown','BC'),
  ('Chinatown','BC'),
  ('Chomedey','QC'),
  ('Christopher-Champlain','ON'),
  ('Church-Yonge Corridor','ON'),
  ('Châteauguay','QC'),
  ('Clairlea-Birchmount','ON'),
  ('Clanton Park','ON'),
  ('Clarence-Rockland','ON'),
  ('Clayton Park West','NS'),
  ('Cliffcrest','ON'),
  ('Cloverdale','BC'),
  ('Cobourg','ON'),
  ('Cochrane','AB'),
  ('Cole Harbour','NS'),
  ('Collingwood','ON'),
  ('Colwood','BC'),
  ('Conception Bay South','NL'),
  ('Confederation','SK'),
  ('Coquitlam','BC'),
  ('Coquitlam Town Centre','BC'),
  ('Coquitlam West','BC'),
  ('Core Neighbourhoods','SK'),
  ('Corner Brook','NL'),
  ('Cornwall','ON'),
  ('Courtenay','BC'),
  ('Coventry Hills','AB'),
  ('Cranbrook','BC'),
  ('Cranston','AB'),
  ('Côte-Saint-Luc','QC'),
  ('Danforth East York','ON'),
  ('Dartmouth','NS'),
  ('Delta','BC'),
  ('Desmarchais-Crawford','QC'),
  ('Deux-Montagnes','QC'),
  ('Dewdney East','SK'),
  ('Dieppe','NB'),
  ('Dollard-Des Ormeaux','QC'),
  ('Don Valley Village','ON'),
  ('Dorset Park','ON'),
  ('Dorval','QC'),
  ('Dovercourt-Wallace Emerson-Junction','ON'),
  ('Downsview-Roding-CFB','ON'),
  ('Downtown Eastside','BC'),
  ('Downtown Halifax','NS'),
  ('Downtown Vancouver','BC'),
  ('Drummondville','QC'),
  ('Dunbar-Southlands','BC'),
  ('Duncan','BC'),
  ('Duvernay','QC'),
  ('East End-Danforth','ON'),
  ('East Gwillimbury','ON'),
  ('East Hastings','BC'),
  ('Edenbridge-Humber Valley','ON'),
  ('Edgemont','AB'),
  ('Edmonds','BC'),
  ('Edmonton','AB'),
  ('Edmundston','NB'),
  ('Eglinton East','ON'),
  ('Englemount-Lawrence','ON'),
  ('Eringate-Centennial-West Deane','ON'),
  ('Esquimalt','BC'),
  ('Etobicoke','ON'),
  ('Evanston','AB'),
  ('Evergreen','AB'),
  ('Fairview','BC'),
  ('Fallingbrook','ON'),
  ('Fergus','ON'),
  ('Fiddlesticks','ON'),
  ('Fleetwood','BC'),
  ('Flemingdon Park','ON'),
  ('Forest Heights','ON'),
  ('Fort Erie','ON'),
  ('Fort Garry South','MB'),
  ('Fort McMurray','AB'),
  ('Fort St. John','BC'),
  ('Fraser Heights','BC'),
  ('Fredericton','NB'),
  ('Fredericton Northside','NB'),
  ('Gatineau','QC'),
  ('Georgetown','ON'),
  ('Glace Bay','NS'),
  ('Glenfield-Jane Heights','ON'),
  ('Gloucester','ON'),
  ('Gordon Head','BC'),
  ('Granby','QC'),
  ('Grande Prairie','AB'),
  ('Grandview-Woodlands','BC'),
  ('Greater Napanee','ON'),
  ('Greater Sudbury','ON'),
  ('Greenfield Park','QC'),
  ('Grimsby','ON'),
  ('Guelph','ON'),
  ('Guildford','BC'),
  ('Halifax','NS'),
  ('Halifax South End','NS'),
  ('Halifax West End','NS'),
  ('Halton Hills','ON'),
  ('Hamilton','ON'),
  ('Haney','BC'),
  ('Harewood','BC'),
  ('Hastings-Sunrise','BC'),
  ('Henry Farm','ON'),
  ('Hespeler','ON'),
  ('High Park North','ON'),
  ('High Park-Swansea','ON'),
  ('Hillcrest Village','ON'),
  ('Hull','QC'),
  ('Humbermede','ON'),
  ('Huntsville','ON'),
  ('Ile-des-Soeurs','QC'),
  ('Innisfil','ON'),
  ('Islington-City Centre West','ON'),
  ('Joliette','QC'),
  ('Jonquière','QC'),
  ('Kamloops','BC'),
  ('Kanata','ON'),
  ('Kelowna','BC'),
  ('Kennedy Park','ON'),
  ('Kenora','ON'),
  ('Kensington-Cedar Cottage','BC'),
  ('Kensington-Chinatown','ON'),
  ('Keswick','ON'),
  ('Killarney','BC'),
  ('Kingston','ON'),
  ('Kingsview Village-The Westway','ON'),
  ('Kingsville','ON'),
  ('Kirkland','QC'),
  ('Kitchener','ON'),
  ('Kitsilano','BC'),
  ('L''Amoreaux','ON'),
  ('L''Ancienne-Lorette','QC'),
  ('L''Assomption','QC'),
  ('L''Île-Bizard–Sainte-Geneviève','QC'),
  ('La Cité-Limoilou','QC'),
  ('La Haute-Saint-Charles','QC'),
  ('La Prairie','QC'),
  ('LaSalle','ON'),
  ('Ladner','BC'),
  ('Laflèche','QC'),
  ('Lake Country','BC'),
  ('Lakewood','SK'),
  ('Langford','BC'),
  ('Langley','BC'),
  ('Lansing-Westgate','ON'),
  ('Laval','QC'),
  ('Laval-des-Rapides','QC'),
  ('Lawrence Park South','ON'),
  ('Lawson','SK'),
  ('Le Plateau-Mont-Royal','QC'),
  ('Le Sud-Ouest','QC'),
  ('Le Vieux-Longueuil','QC'),
  ('Leamington','ON'),
  ('Leaside-Bennington','ON'),
  ('Leduc','AB'),
  ('Les Coteaux','QC'),
  ('Les Rivières','QC'),
  ('Lethbridge','AB'),
  ('Lindsay','ON'),
  ('Little Portugal','ON'),
  ('Lloydminster','AB'),
  ('London','ON'),
  ('Longueuil','QC'),
  ('Lougheed','BC'),
  ('Lower Lonsdale','BC'),
  ('Lower Sackville','NS'),
  ('Lutes Mountain','NB'),
  ('Lévis','QC'),
  ('Magog','QC'),
  ('Maillardville','BC'),
  ('Malvern','ON'),
  ('Maple Ridge','BC'),
  ('Markham','ON'),
  ('Marpole','BC'),
  ('Mascouche','QC'),
  ('Maywood','BC'),
  ('McKenzie Towne','AB'),
  ('Medicine Hat','AB'),
  ('Mercier–Hochelaga-Maisonneuve','QC'),
  ('Metrotown','BC'),
  ('Midland','ON'),
  ('Mile End','QC'),
  ('Milliken','ON'),
  ('Milton','ON'),
  ('Mimico','ON'),
  ('Mirabel','QC'),
  ('Miramichi','NB'),
  ('Mission','BC'),
  ('Mississauga','ON'),
  ('Moncton','NB'),
  ('Mont-Royal','QC'),
  ('Mont-Saint-Hilaire','QC'),
  ('Montréal','QC'),
  ('Montréal-Nord','QC'),
  ('Moose Jaw','SK'),
  ('Morningside','ON'),
  ('Moss Park','ON'),
  ('Mount Olive-Silverstone-Jamestown','ON'),
  ('Mount Pearl','NL'),
  ('Mount Pleasant','BC'),
  ('Mount Pleasant East','ON'),
  ('Mount Pleasant West','ON'),
  ('Mt Pleasant','BC'),
  ('Nanaimo','BC'),
  ('Nepean','ON'),
  ('Neufchâtel-Est–Lebourgneuf','QC'),
  ('New Glasgow','NS'),
  ('New Westminster','BC'),
  ('Newmarket','ON'),
  ('Newton','BC'),
  ('Newtonbrook East','ON'),
  ('Newtonbrook West','ON'),
  ('Niagara','ON'),
  ('Niagara Falls','ON'),
  ('Niagara-on-the-Lake','ON'),
  ('Norfolk County','ON'),
  ('North Battleford','SK'),
  ('North Bay','ON'),
  ('North Cowichan','BC'),
  ('North Delta','BC'),
  ('North St.James Town','ON'),
  ('North Vancouver','BC'),
  ('Notre-Dame-de-Grâce','QC'),
  ('Nutana Sector','SK'),
  ('O''Connor-Parkview','ON'),
  ('Oak Bay','BC'),
  ('Oakville','ON'),
  ('Oakwood Village','ON'),
  ('Okanagan Mission','BC'),
  ('Okotoks','AB'),
  ('Orangeville','ON'),
  ('Orillia','ON'),
  ('Orléans','ON'),
  ('Oshawa','ON'),
  ('Ottawa','ON'),
  ('Ottawa South','ON'),
  ('Outremont','QC'),
  ('Owen Sound','ON'),
  ('Panorama Hills','AB'),
  ('Paradise','NL'),
  ('Parc-Extension','QC'),
  ('Parkwoods-Donalda','ON'),
  ('Penticton','BC'),
  ('Petawawa','ON'),
  ('Peterborough','ON'),
  ('Pickering','ON'),
  ('Pierrefonds','QC'),
  ('Pierrefonds-Roxboro','QC'),
  ('Pitt Meadows','BC'),
  ('Pleasant View','ON'),
  ('Pointe-Claire','QC'),
  ('Port Alberni','BC'),
  ('Port Colborne','ON'),
  ('Port Coquitlam','BC'),
  ('Port Moody','BC'),
  ('Prince Albert','SK'),
  ('Prince Edward','ON'),
  ('Prince George','BC'),
  ('Quinte West','ON'),
  ('Quispamsis','NB'),
  ('Québec','QC'),
  ('Red Deer','AB'),
  ('Regina','SK'),
  ('Renfrew Heights','BC'),
  ('Renfrew-Collingwood','BC'),
  ('Repentigny','QC'),
  ('Richmond','BC'),
  ('Richmond Hill','ON'),
  ('Riley Park','BC'),
  ('Rimouski','QC'),
  ('Riverview','NB'),
  ('Rivière-des-Prairies–Pointe-aux-Trembles','QC'),
  ('Rivière-du-Loup','QC'),
  ('Rock Forest','QC'),
  ('Rockcliffe-Smythe','ON'),
  ('Rosedale-Moore Park','ON'),
  ('Rosemont–La Petite-Patrie','QC'),
  ('Rouge','ON'),
  ('Rouyn-Noranda','QC'),
  ('Rutland','BC'),
  ('Saanich','BC'),
  ('Saddle Ridge','AB'),
  ('Saguenay','QC'),
  ('Saint John','NB'),
  ('Saint John West','NB'),
  ('Saint-Augustin-de-Desmaures','QC'),
  ('Saint-Basile-le-Grand','QC'),
  ('Saint-Bruno-de-Montarville','QC'),
  ('Saint-Charles-Borromée','QC'),
  ('Saint-Constant','QC'),
  ('Saint-Eustache','QC'),
  ('Saint-Georges','QC'),
  ('Saint-Henri','QC'),
  ('Saint-Hubert','QC'),
  ('Saint-Hyacinthe','QC'),
  ('Saint-Jean-sur-Richelieu','QC'),
  ('Saint-Jérôme','QC'),
  ('Saint-Laurent','QC'),
  ('Saint-Lazare','QC'),
  ('Saint-Lin-Laurentides','QC'),
  ('Saint-Louis-de-Terrebonne','QC'),
  ('Saint-Léonard','QC'),
  ('Saint-Michel','QC'),
  ('Saint-Vincent-de-Paul','QC'),
  ('Sainte-Catherine','QC'),
  ('Sainte-Foy','QC'),
  ('Sainte-Julie','QC'),
  ('Sainte-Thérèse','QC'),
  ('Salaberry-de-Valleyfield','QC'),
  ('Salmon Arm','BC'),
  ('Sarnia','ON'),
  ('Saskatoon','SK'),
  ('Sault Ste. Marie','ON'),
  ('Scarborough Village','ON'),
  ('Seafair','BC'),
  ('Sept-Îles','QC'),
  ('Shawinigan','QC'),
  ('Sherbrooke','QC'),
  ('Sherwood Park','AB'),
  ('Snowdon','QC'),
  ('Sooke','BC'),
  ('Sorel-Tracy','QC'),
  ('South Granville','BC'),
  ('South Parkdale','ON'),
  ('South Riverdale','ON'),
  ('South Surrey','BC'),
  ('Spruce Grove','AB'),
  ('Squamish','BC'),
  ('St. Albert','AB'),
  ('St. Andrew-Windfields','ON'),
  ('St. Catharines','ON'),
  ('St. James-Assiniboia East','MB'),
  ('St. John''s','NL'),
  ('St. Thomas','ON'),
  ('Steeles','ON'),
  ('Steinbach','MB'),
  ('Steveston','BC'),
  ('Stittsville','ON'),
  ('Stonebridge','SK'),
  ('Stonegate-Queensway','ON'),
  ('Stoney Creek','ON'),
  ('Stony Plain','AB'),
  ('Stouffville','ON'),
  ('Stratford','ON'),
  ('Strathroy','ON'),
  ('Strawberry Hill','BC'),
  ('Sunset','BC'),
  ('Surrey','BC'),
  ('Surrey City Centre','BC'),
  ('Swift Current','SK'),
  ('Sydney','NS'),
  ('Sylvan Lake','AB'),
  ('Tam O''Shanter-Sullivan','ON'),
  ('Taradale','AB'),
  ('Taylor-Massey','ON'),
  ('Tecumseh','ON'),
  ('Templeton-Est','QC'),
  ('Terrace','BC'),
  ('Terrebonne','QC'),
  ('The Beaches','ON'),
  ('Thetford-Mines','QC'),
  ('Thorncliffe Park','ON'),
  ('Thorold','ON'),
  ('Thunder Bay','ON'),
  ('Tillsonburg','ON'),
  ('Timmins','ON'),
  ('Toronto','ON'),
  ('Townline','BC'),
  ('Trinity-Bellwoods','ON'),
  ('Trois-Rivières','QC'),
  ('Tsawwassen','BC'),
  ('Tuscany','AB'),
  ('University Endowment Lands','BC'),
  ('University Heights','SK'),
  ('Uxbridge','ON'),
  ('Val-d''Or','QC'),
  ('Val-des-Arbres','QC'),
  ('Valley East','ON'),
  ('Vancouver','BC'),
  ('Vanier','ON'),
  ('Varennes','QC'),
  ('Vaudreuil-Dorion','QC'),
  ('Vaughan','ON'),
  ('Vedder Crossing','BC'),
  ('Verdun','QC'),
  ('Vernon','BC'),
  ('Victoria','BC'),
  ('Victoria Village','ON'),
  ('Victoria-Downtown','BC'),
  ('Victoria-Fraserview','BC'),
  ('Victoriaville','QC'),
  ('Ville-Marie','QC'),
  ('Ville-Émard','QC'),
  ('Villeray–Saint-Michel–Parc-Extension','QC'),
  ('Walnut Grove','BC'),
  ('Wasaga Beach','ON'),
  ('Waterdown','ON'),
  ('Waterfront Communities-The Island','ON'),
  ('Waterloo','ON'),
  ('Welland','ON'),
  ('West End','BC'),
  ('West Hill','ON'),
  ('West Humber-Clairville','ON'),
  ('West Kelowna','BC'),
  ('West Vancouver','BC'),
  ('Westminster-Branson','ON'),
  ('Westmount','QC'),
  ('Weston','ON'),
  ('Westwood Plateau','BC'),
  ('Wexford/Maryvale','ON'),
  ('Whalley','BC'),
  ('Whitby','ON'),
  ('Whitchurch-Stouffville','ON'),
  ('White Rock','BC'),
  ('Whitehorse','YT'),
  ('Willoughby','BC'),
  ('Willowdale','ON'),
  ('Willowdale East','ON'),
  ('Willowdale West','ON'),
  ('Willowridge-Martingrove-Richview','ON'),
  ('Windsor','ON'),
  ('Winnipeg','MB'),
  ('Woburn','ON'),
  ('Woodlawn','NS'),
  ('Woodstock','ON'),
  ('Wîhkwêntôwin','AB'),
  ('Yellowknife','NT'),
  ('York University Heights','ON'),
  ('Yorkton','SK')
)
update public.cities c
   set region = m.code, admin1 = m.code
  from m
 where c.country_code = 'CA'
   and c.name = m.name
   and (c.region is null or c.region <> m.code);

-- Leaving one behind would put a hole in the middle of the new picker.
do $$
declare n integer;
begin
  select count(*) into n from public.cities where country_code = 'CA' and region is null;
  if n > 0 then
    raise exception '% Canadian cities still have no province', n;
  end if;
end $$;
